[versions]
kotlin = "1.8.22"

minecraft = "1.19.2"
fapi = "0.76.0+1.19.2"
flk = "1.9.6+kotlin.1.8.22"
loader = "0.14.21"
mappings = "1.19.2+build.22"
loom = "1.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fapi" }

fabric_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "flk" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "mappings" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabric_loom = { id = "fabric-loom", version.ref = "loom" }
